### ISSUE TITLE
Token based authentication for mobile users

### ISSUE THREAD

**Issue by vaibhavglokhande** [payumyac/basic_masters#2]
> The mobile app uses RESTful services to communicate with the server and all data operations. Currently, the user requests are not authenticated or authorized by the server. So token-based authentication has to be implemented.

Reference: [link](https://www.yiiframework.com/doc/guide/2.0/en/rest-authentication) to setup  authentication for RESTful web-services in Yii framework.

### TODO

- [x] Create a new model to manage student tokens.

- [x] Create a new `StudentIdentity` class which implements `yii\web\IdentityInterface` to enable token-based identification and validation.
- [x] Setup new user component in `config/web.php` for `StudentIdentity` class.
- [x] Disable session management for `Student` to disable cookie-based authentication and enable token-based authentication.
- [x] Implement the `behaviours` method in controllers which provide RESTful APIs and allow both token-based as well as username: password authentication.
- [x] Exclude actions which don't require authentication.

**Implement methods required for token-based authentication**
- [x] Create a method to save a new token whenever a user login. Allow only one token, destroy any previous token on new login.
- [x] Create a method to invalidate all tokens when user logout.
-  ~Create a method to provide user identity based on the supplied token and restrict access to other users' data.~ New issue #3 created for this.
-  ~Create a method to invalidate all tokens when a user changes password.~ Change password not yet implemented.
